apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: jenkins-pv
  labels:
    tier: volume
    app: giftit
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/jenkins_home"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-giftit-pool-1-3395c556-fkvo

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: giftit-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#   - ReadWriteOnce
#   gcePersistentDisk:
#     pdName: slow
#     fsType: ext4
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - northamerica-northeast1-a


          