apiVersion: v1
kind: Service
metadata:
  name: service-jenkins-giftit
  labels:
    app: giftit-jenkins
    environment: minikube
spec:
  selector:
    app: giftit
    environment: minikube
    tier: Jenkins
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP