apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

# ---

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: slow
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-standard
#   fstype: ext4
#   replication-type: none