apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: giftit-pvc
  labels:
    app: giftit
    tier: volume
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi




#       kubectl --kubeconfig ~/.kube/config get secrets -n  ssh-keys \
# -o jsonpath='{.data.ssh\.key}' | base64 -d > \
# ~/.ssh/[USER_CLUSTER_NAME].key && chmod 600 ~/.ssh/[USER_CLUSTER_NAME].key